version: '2.1'
services:
   service:
     image: kvalitetsit/vdx-example-java:latest
     environment:
       - sts.url.wsdl=https://sts.vconf-stage.dk/sts/sts.wsdl
       - service.url=https://videoapi.vconf-stage.dk/videoapi
       - sts.properties=/app/sts.properties
       - keystore.password=Test1234
       - keystore.path=/app/client.jks
     volumes:
       - ../../../sts.properties:/app/sts.properties:ro
       - ../../../client.jks:/app/client.jks:ro
     ports:
       - "8080:8080"
   documenatation-and-test:
     image: kvalitetsit/vdx-example-java-documentation:latest
     environment:
       SERVER_URLS: '[{"url": "http://localhost:8080"}]'
     ports:
      - "80:8080"
